add reads from jaeger-span-saved
helios/jaeger pull request #6
Opened 2022-07-27 13:05 UTC by levyoren

2022-07-27 14:26 UTC, prsnca requested changes

2022-07-27 14:26 UTC, prsnca commented on plugin/storage/es/spanstore/reader_test.go
> +				"jaeger-span-saved",
can we put it in some const in the code?

2022-07-27 14:56 UTC, nata7che commented on plugin/storage/es/spanstore/reader_test.go
> +				"jaeger-span-saved",
+1

2022-07-27 15:46 UTC, levyoren commented on plugin/storage/es/spanstore/reader_test.go
> +				"jaeger-span-saved",
done - thanks.

2022-07-28 06:00 UTC, nata7che approved these changes

2022-07-31 08:14 UTC, prsnca commented on .github/workflows/ci-unit-tests.yml
> +    # - name: Upload coverage to codecov
why not just delete this?

2022-08-02 08:55 UTC, levyoren commented on .github/workflows/ci-unit-tests.yml
> +    # - name: Upload coverage to codecov
done.

2022-08-02 13:29 UTC, prsnca requested changes

2022-08-02 13:29 UTC, prsnca commented on .github/workflows/deploy.yml
> +                  AIRBRAKE_PROJECT_ID: 380559
you can remove the airbrake params

2022-08-02 13:31 UTC, prsnca approved these changes

2022-08-02 13:32 UTC, merged